### ISSUE TITLE
Mobile version: Dates in the last quarter of the month can only be entered, if the phone is turned by 90°

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#43] opened 2020-08-14 09:26 UTC
On the mobile screen version, when entering an observation date, it is not possible to select a date in the second half of the month (screen is too small and the calendar view can't be "scrolled down"). It is, thus, only possible to enter such an observation date on the phone when the phone is turned by 90°. This problem is appearing in the "real version" of the App, but strangely, in the TestApp, the calendar is correctly displayed.

TestApp (the way it should be):
![Foto 14 08 20, 11 21 47](https://user-images.githubusercontent.com/65400300/90234927-c4c84380-de20-11ea-8b3c-d493e13fcd4f.png)

Real App (problem):
![Foto 14 08 20, 11 23 16](https://user-images.githubusercontent.com/65400300/90234965-d3aef600-de20-11ea-8590-e97744e48afa.png)

Real App- when mobile phone is turned by 90°:
![Foto 14 08 20, 11 25 40](https://user-images.githubusercontent.com/65400300/90235068-f9d49600-de20-11ea-8b63-04ff5d2399c3.png)

**Comment by pgoellnitz** [comment] 2020-08-14 13:07
The calendar component seems not to play nice with aot compiling. Redeploying the project to production without this option.

@daria-sl: can you please check if the issue is fixed on the production environment?

**Comment by daria-sl** [comment] 2020-08-14 15:41
Unfortunately not.

Daria Lehmann
Wissenschaftliche Mitarbeiterin

[cid:image001.png@01D67262.2567F620]

Verein GLOBE Schweiz
Papiermühlestrasse 172
3003 Bern

Tel.: +41 58 484 96 41<tel:+41%2058%20484%2096%2041>
E-Mail: dlehmann@globe-swiss.ch<mailto:dlehmann@globe-swiss.ch>
Web: www.globe-swiss.ch<http://www.globe-swiss.ch> | www.phaenonet.ch<http://www.phaenonet.ch>

Von: Philippe Göllnitz <notifications@github.com>
Gesendet: Freitag, 14. August 2020 15:08
An: globe-swiss/phaenonet-client <phaenonet-client@noreply.github.com>
Cc: Daria Lehmann <dlehmann@globe-swiss.ch>; Assign <assign@noreply.github.com>
Betreff: Re: [globe-swiss/phaenonet-client] Mobile version: Dates in the last quarter of the month can only be entered, if the phone is turned by 90° (#43)


The calendar component seems not to play nice with aot compiling. Redeploying the project to production without this option.

@daria-sl<https://github.com/daria-sl>: can you please check if the issue is fixed on the production environment?

**Comment by pgoellnitz** [comment] 2020-08-19 18:11
@daria-sl, I added touch device support for the datepicker for small screen sizes. For me it looked good but please test again on your devices (mobile and desktop).

**Comment by daria-sl** [comment] 2020-08-21 07:29
On the test application, the calendar is now displayed well, while on the small laptop (1920x1080), the last line of the calendar is not visible.

**Closed** 2020-08-21 07:57 UTC
Labels: bug
